#!/bin/bash

echo "Introduzca el nombre del proyecto:[$FILE_TO_COMPILE]"
read filename

if [ "$filename" !=  '' ]; then
   export FILE_TO_COMPILE=$filename
fi

echo "Fichero a compilar:$FILE_TO_COMPILE"



#exit 0
